version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - .:/appd