# Generated by Django 4.2.2 on 2023-06-24 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tax_id', models.CharField(max_length=14)),
                ('loan_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('status', models.IntegerField(choices=[(1, 'APROVADO'), (2, 'NEGADO')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('number', models.CharField(blank=True, max_length=6, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='djangoapp.profileclient')),
            ],
        ),
    ]
