# Generated by Django 4.2.2 on 2023-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileclient',
            name='status',
            field=models.IntegerField(choices=[(1, 'APROVADO'), (2, 'NEGADO'), (0, 'PENDING')], default=0),
        ),
    ]
